name: pinterest_clone
description: This is Pinterest clone


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-168.0.dev <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  # for design
  cupertino_icons: ^1.0.2

  # connect network
  http: ^0.13.4
  http_interceptor: ^1.0.2
  dio: ^4.0.6

  # database
  hive_flutter: ^1.1.0

  #permission android OS
  permission_handler: ^10.0.0

  #strage
  flutter_cache_manager: ^3.3.0
  image_gallery_saver: ^1.7.1


  # image
  cached_network_image: ^3.2.1
  transparent_image: ^2.0.0
  image_picker: ^0.8.5+3

  # decoration
  flutter_staggered_grid_view: ^0.6.2
  flutter_wallpaper_manager: ^0.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
